# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-11 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True)),
                ('type', models.CharField(choices=[('income', 'Income'), ('expenditure', 'Expenditure')], max_length=20)),
                ('money', models.FloatField(max_length=20)),
                ('giving_party', models.CharField(max_length=100)),
                ('recieving_party', models.CharField(max_length=100)),
            ],
        ),
    ]
